name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run builds
      run: npm run server:build & npm run client:build &

    - name: Run integration tests
      env: 
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        PORT: 10000
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: integration # This makes the deploy job wait for the integration job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run builds
      run: npm run server:build & npm run client:build &

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{"serviceId": "csvmsuhopnds738bp4o0", "branch": "main"}' \
          https://api.render.com/v1/services/csvmsuhopnds738bp4o0/deploys